name = "Yinyang"
license = "MIT"
licenselink = "https://github.com/joway/hugo-theme-yinyang/blob/master/LICENSE"
description = "Yinyang theme for Hugo."
homepage = "https://github.com/joway/hugo-theme-yinyang"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = ["blog"]
min_version = "0.50"

[params]
staticPrefix = ""
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []

[author]
  name = "Joway Wang"
  homepage = "https://joway.io"
